-- Supabase/PostgreSQL full schema for the Business project
-- Run this file in Supabase SQL Editor.

begin;

create extension if not exists pgcrypto;

-- Keep updated_at current on updates.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new; 
end;
$$;

-- =========================
-- Core users and customers
-- =========================
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  name text not null,
  email text not null unique,
  password_hash text,
  role text not null default 'buyer' check (role in ('buyer','admin','staff','farmer','driver')),
  status text not null default 'active' check (status in ('active','inactive','suspended')),
  suspended boolean not null default false,
  phone text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id bigint unique references public.users(id) on delete set null,
  external_customer_code text unique,
  loyalty_tier text not null default 'Regular' check (loyalty_tier in ('Regular','Silver','Gold','Platinum')),
  loyalty_points integer not null default 0,
  total_orders integer not null default 0,
  total_spent numeric(12,2) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_points_log (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  event_type text not null check (event_type in ('earned','spent','adjusted')),
  points integer not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_interactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  interaction_type text not null,
  notes text,
  interaction_date timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  subject text not null,
  complaint_text text not null,
  status text not null default 'open' check (status in ('open','in_progress','resolved','closed')),
  priority text not null default 'medium' check (priority in ('low','medium','high')),
  admin_response text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- Catalog, inventory, carts
-- =========================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image text,
  category text,
  unit text,
  price numeric(12,2) not null,
  stock integer not null default 0,
  reorder_threshold integer not null default 0,
  farm_name text,
  region text,
  organic boolean not null default false,
  status text not null default 'active' check (status in ('active','inactive')),
  approval_status text not null default 'pending' check (approval_status in ('pending','approved','rejected')),
  approval_note text,
  is_featured boolean not null default false,
  promotion_text text,
  discount_percent numeric(5,2) not null default 0,
  calories integer,
  protein numeric(8,2),
  fat numeric(8,2),
  carbs numeric(8,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  movement_type text not null check (movement_type in ('in','out','adjustment','rejected')),
  quantity integer not null,
  note text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(cart_id, product_id)
);

-- =========================
-- Orders and payments
-- =========================
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique,
  user_id bigint references public.users(id) on delete set null,
  customer_name text not null,
  customer_phone text,
  address text not null,
  zone text,
  delivery_slot text,
  driver_id bigint,
  total_price numeric(12,2) not null,
  status text not null default 'pending' check (status in ('pending','placed','confirmed','shipped','out_for_delivery','delivered','completed','cancelled')),
  fulfillment_status text not null default 'Confirmed',
  dispute_status text not null default 'none' check (dispute_status in ('none','open','under_review','resolved','rejected')),
  dispute_note text,
  payment_status text not null default 'Paid' check (payment_status in ('pending','paid','failed','partially_refunded','refunded')),
  payment_method text,
  payment_reference text,
  receipt jsonb,
  cancellation_reason text,
  cancelled_at timestamptz,
  cancelled_by text,
  refund_total numeric(12,2) not null default 0,
  placed_at timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_timeline (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  event_type text not null,
  actor text,
  status text,
  fulfillment_status text,
  note text,
  refund_amount numeric(12,2),
  dispute_status text,
  happened_at timestamptz not null default now()
);

create table if not exists public.order_refunds (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  amount numeric(12,2) not null,
  refund_type text not null check (refund_type in ('partial','full')),
  reason text,
  actor text,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  transaction_code text unique,
  order_id bigint references public.orders(id) on delete set null,
  customer_name text,
  amount numeric(12,2) not null,
  payment_method text,
  status text not null check (status in ('success','pending','failed')),
  gateway_response jsonb,
  retries integer not null default 0,
  created_at timestamptz not null default now()
);

-- =========================
-- Delivery operations
-- =========================
create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  driver_code text unique,
  name text not null,
  phone text,
  vehicle_plate text,
  zone text,
  status text not null default 'Available' check (status in ('Available','On Delivery','Off Duty','Suspended')),
  current_order_id bigint references public.orders(id) on delete set null,
  deliveries_completed_today integer not null default 0,
  total_deliveries integer not null default 0,
  average_per_day numeric(8,2) not null default 0,
  complaints_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.driver_deliveries (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.drivers(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  address text,
  status text not null check (status in ('Assigned','Out for Delivery','Delivered','Failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.delivery_slots (
  id bigint generated by default as identity primary key,
  slot_label text not null unique,
  max_orders integer not null default 0,
  is_open boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- Farmers and payouts
-- =========================
create table if not exists public.farmers (
  id bigint generated by default as identity primary key,
  farmer_code text unique,
  name text not null,
  farm_name text not null,
  region text,
  products_supplied text,
  quality_score numeric(4,2),
  total_batches integer not null default 0,
  rejected_batches integer not null default 0,
  status text not null default 'Pending' check (status in ('Pending','Approved','Suspended','Rejected')),
  phone text,
  payout_account text,
  total_value_supplied numeric(12,2) not null default 0,
  total_rejections integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.farmer_batches (
  id bigint generated by default as identity primary key,
  farmer_id bigint not null references public.farmers(id) on delete cascade,
  batch_code text unique,
  product_name text not null,
  quantity numeric(12,2) not null,
  harvest_date date,
  delivery_date date,
  quality_check text,
  accepted_quantity numeric(12,2) default 0,
  rejected_quantity numeric(12,2) default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.farmer_payouts (
  id bigint generated by default as identity primary key,
  farmer_id bigint not null references public.farmers(id) on delete cascade,
  period_label text not null,
  amount numeric(12,2) not null,
  status text not null check (status in ('Pending','Processing','Paid','Failed')),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- Support and CRM campaigns
-- =========================
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  ticket_code text unique,
  user_id bigint references public.users(id) on delete set null,
  customer_name text,
  order_id bigint references public.orders(id) on delete set null,
  issue_type text,
  priority text not null default 'Medium' check (priority in ('Low','Medium','High')),
  assigned_to text,
  status text not null default 'Open' check (status in ('Open','In Progress','Resolved','Closed')),
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  sender_type text not null check (sender_type in ('customer','staff','system')),
  message text not null,
  sent_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  campaign_code text unique,
  name text not null,
  target_segment text,
  channel text,
  scheduled_date timestamptz,
  status text not null default 'Draft' check (status in ('Draft','Scheduled','Sent','Paused','Cancelled')),
  messages_sent integer not null default 0,
  orders_generated integer not null default 0,
  open_rate numeric(6,2) not null default 0,
  revenue_attributed numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_triggers (
  id bigint generated by default as identity primary key,
  trigger_type text not null,
  channel text not null,
  target_user_id bigint references public.users(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'queued' check (status in ('queued','processing','sent','failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- Config and dashboard meta
-- =========================
create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  setting_key text not null unique,
  setting_value jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Optional: lightweight table used by current Supabase test page.
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  is_done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- Indexes
-- =========================
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_products_status on public.products(status);
create index if not exists idx_products_approval_status on public.products(approval_status);
create index if not exists idx_customer_interactions_user_id on public.customer_interactions(user_id);
create index if not exists idx_complaints_user_id on public.complaints(user_id);
create index if not exists idx_support_tickets_status on public.support_tickets(status);
create index if not exists idx_notification_triggers_status on public.notification_triggers(status);
create index if not exists idx_payment_transactions_status on public.payment_transactions(status);

-- =========================
-- updated_at triggers
-- =========================
drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_customers_updated_at on public.customers;
create trigger trg_customers_updated_at before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists trg_complaints_updated_at on public.complaints;
create trigger trg_complaints_updated_at before update on public.complaints
for each row execute function public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_carts_updated_at on public.carts;
create trigger trg_carts_updated_at before update on public.carts
for each row execute function public.set_updated_at();

drop trigger if exists trg_cart_items_updated_at on public.cart_items;
create trigger trg_cart_items_updated_at before update on public.cart_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists trg_drivers_updated_at on public.drivers;
create trigger trg_drivers_updated_at before update on public.drivers
for each row execute function public.set_updated_at();

drop trigger if exists trg_driver_deliveries_updated_at on public.driver_deliveries;
create trigger trg_driver_deliveries_updated_at before update on public.driver_deliveries
for each row execute function public.set_updated_at();

drop trigger if exists trg_delivery_slots_updated_at on public.delivery_slots;
create trigger trg_delivery_slots_updated_at before update on public.delivery_slots
for each row execute function public.set_updated_at();

drop trigger if exists trg_farmers_updated_at on public.farmers;
create trigger trg_farmers_updated_at before update on public.farmers
for each row execute function public.set_updated_at();

drop trigger if exists trg_farmer_batches_updated_at on public.farmer_batches;
create trigger trg_farmer_batches_updated_at before update on public.farmer_batches
for each row execute function public.set_updated_at();

drop trigger if exists trg_farmer_payouts_updated_at on public.farmer_payouts;
create trigger trg_farmer_payouts_updated_at before update on public.farmer_payouts
for each row execute function public.set_updated_at();

drop trigger if exists trg_support_tickets_updated_at on public.support_tickets;
create trigger trg_support_tickets_updated_at before update on public.support_tickets
for each row execute function public.set_updated_at();

drop trigger if exists trg_campaigns_updated_at on public.campaigns;
create trigger trg_campaigns_updated_at before update on public.campaigns
for each row execute function public.set_updated_at();

drop trigger if exists trg_notification_triggers_updated_at on public.notification_triggers;
create trigger trg_notification_triggers_updated_at before update on public.notification_triggers
for each row execute function public.set_updated_at();

drop trigger if exists trg_app_settings_updated_at on public.app_settings;
create trigger trg_app_settings_updated_at before update on public.app_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_todos_updated_at on public.todos;
create trigger trg_todos_updated_at before update on public.todos
for each row execute function public.set_updated_at();

-- =========================
-- Seed minimal baseline rows
-- =========================
insert into public.app_settings (setting_key, setting_value)
values
  ('delivery', '{"fee":15,"minimumOrder":50,"zones":["North Accra","East Legon","Osu","Tema","Airport"]}'::jsonb),
  ('loyalty', '{"pointsPerGhc":1,"silver":250,"gold":500,"platinum":900}'::jsonb),
  ('finance', '{"vat":15,"payoutDay":"Friday","platformCommissionRate":12.5}'::jsonb)
on conflict (setting_key) do nothing;

insert into public.delivery_slots (slot_label, max_orders, is_open)
values
  ('8 to 10 AM', 20, true),
  ('10 AM to 12 PM', 28, true),
  ('12 to 2 PM', 26, true),
  ('2 to 4 PM', 24, false),
  ('4 to 6 PM', 18, true),
  ('6 to 8 PM', 14, false)
on conflict (slot_label) do nothing;

insert into public.todos (name)
values ('Initial Supabase connection check')
on conflict do nothing;

commit;
